server:
  port: 8090


eureka:
  client:
    register-with-eureka: false #先声明不向eureka中注册自己
    serviceUrl:
      defaultZone: http://localhost:7001/eureka
  #    defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

